name: Create Pre Release Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+-preview.[0-9]+.[0-9]+.[0-9]"

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4

      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV

      - name: Download References
        shell: pwsh
        run: |
          .\Download-References.ps1

      - name: Build DLLs - Oxide
        run: dotnet build Rust.UIFramework.csproj -c Release /p:Platform=Oxide /p:Version=$VERSION -f net48
        working-directory: src/Rust.UIFramework

      - name: Build DLLs - Carbon
        run: dotnet build Rust.UIFramework.csproj -c Release /p:Platform=Carbon /p:Version=$VERSION -f net48
        working-directory: src/Rust.UIFramework

      - name: Move DLLs
        run: |
          mkdir -p bin
          mv Rust.UIFramework/bin/Oxide/Release/net48/Oxide.Ext.UiFramework.dll bin/
          mv Rust.UIFramework/bin/Carbon/Release/net48/Carbon.Ext.UiFramework.dll bin/
        working-directory: src

      - name: Upload Release Assets
        run: |
          $TAG=($env:GITHUB_REF -replace 'refs/tags/', '')
          $dllPath = Get-ChildItem -Path src/bin -Filter *.dll -File | Select-Object -ExpandProperty FullName
          gh release upload $TAG $dllPath
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
